### ISSUE TITLE
Informative ValueError

### ISSUE THREAD

**Issue by peonor** [ericchansen/q2mm#21]
When running with -mgeig with multiple pairs, I get the error "ValueError: matrices are not aligned", it would be very helpful to also get the output about WHICH pair this is for. Now I have to run all 25 one at a time until I find the error...

**Comment by ericchansen** [comment]
I will update the error message in a few minutes here.

Also, I bet you that this error is due to dummy atom identification. I resolved this in commit ed94ae028facc8f89094 of sort, which I actually just merged into my master. A [pull request](https://github.com/Q2MM/q2mm/pull/4) is also up for Q2MM/q2mm.

**Comment by peonor** [comment]
I’m actually playing with the PdAllyls right now, so no dummy atoms. I had included a Gaussian log file without any frequencies in it… Just dumped all of Armita’s, got an error in the transfer somewhere. Went through them by hand, file 22 out of 25 was the only bad one…

Lacking Eigenvectors in the Gaussian file might be another error message.

/Per-Ola

**Comment by ericchansen** [comment]
Z0 has an atomic number of 0 by default, which used to get registered as a dummy atom in Q2MM. I had the exact same problem with some of the Pd structures you provided me awhile ago.

**Comment by peonor** [comment]
OK, haven’t read your code in detail, but why is this a problem? The atomic number is only relevant for the mass, the masses are only relevant in connection with the eigenvectors, and they are available in the QM file, right? With the dummy atom, you have the problem of a mismatch, but not here. Is your code automatically taking out all atoms it perceives as dummies? Should only do that if the eigenvector length is not equal to 3*(the number of atoms in .mae file).

/Per-Ola

**Comment by ericchansen** [comment]
Yes, it removes all atoms it perceives as dummies. The selection code is [here](https://github.com/ericchansen/q2mm/blob/0a4f2c75e1ef36e81a339c1cc0fbf574a44b635b/filetypes.py#L1705-L1725).

Right now I added in this one layer check because it's simple. It's possible to add in another layer of checking before this one like you described, where the looking for which atoms are dummies only occurs if the eigenvector length is not equal to 3N, where N includes the dummies.

This is still a little troubling. In Gaussian .log files, the eigenvector rows corresponding to dummy atoms are zero, so the the overall length still matches 3N (I just double checked this by looking at one of Neil's ferrocene files). In Jaguar, I think that the length is still 3N, but the value is NaN instead of zero, although I'm not sure about this and would have to double check.

I could remove any row that has a value of zero or NaN, but that ignores the case of a real atom having an eigenvector element being zero (albeit unlikely).

**Comment by ericchansen** [comment]
Unless someone has suggestions, I am going to assume that commit ed94ae028facc8f8 (previously mentioned above) is sufficient for closing this issue.
