### ISSUE TITLE
Dangerous torsion-test

### ISSUE THREAD

**Issue by peonor** [ericchansen/q2mm#23]
In filetypes.py, around line 1550, the angles in a torsion are tested for linearity (<5 or >175). The test fails badly if the two angles in the torsion are not included in the optimization set (which can happen). Haven't tried with the very latest version, but since the new "try" statement re-raises the exception, I believe it will fail again.

**Comment by ericchansen** [comment]
Neil and I looked into this a little bit today, but we're not having any luck making this error occur. Do you have any examples?

**Comment by peonor** [comment]
You're rigth, I cannot make it appear either. Must have been another change I wasn't aware of. It's obvious that now self contains all the angles, not just the ones where OPT has been defined. Either this has been changed, or I misunderstood the original error. Closing this.

**Comment by arosale4** [comment]
I think this problem has to do with how the code matches an angle line in an mmo file. When the function read_line_for_angles in filetypes.py tries to match lines in an mmo file it will not match all of the possible lines. For example lines 98, 99, and 102 in the attached mmo file are not matched. I'm assuming it is due to the comment column, but I am no good at regex and can't figure out the exact problem.
[aats1bre.q2mm.mmo.txt](https://github.com/ericchansen/q2mm/files/306795/aats1bre.q2mm.mmo.txt)
[aats1bre inputs.zip](https://github.com/ericchansen/q2mm/files/306796/aats1bre.inputs.zip)

**Comment by arosale4** [comment]
Fixed the problem. RE_SUB in constants.py needs to be able to match commas.
