### ISSUE TITLE
The loop is broken

### ISSUE THREAD

**Issue by peonor** [ericchansen/q2mm#34]
Error in loop.py, using a case with only gradient, at the end of first iteration, get the following:

gradient   -- Copied parameter derivatives from MM3[LAGRANGE F10.0](15138.729388) to MM3[READ](18668.437584).
Traceback (most recent call last):
  File "/home/kcjh508/q2mm/loop.py", line 192, in <module>
    main(sys.argv[1:])
  File "/home/kcjh508/q2mm/loop.py", line 186, in main
    loop.run_loop_input(lines)
  File "/home/kcjh508/q2mm/loop.py", line 108, in run_loop_input
    self.ff = loop.opt_loop()
  File "/home/kcjh508/q2mm/loop.py", line 43, in opt_loop
    change = (last_score - self.ff.score) / last_score
TypeError: unsupported operand type(s) for -: 'NoneType' and 'float'

Seems "last_score" is not initialized. When did this happen? Reproducible, can supply files, but would like to make a smaller case, right now this is at the end of a 118 parameter loop

**Comment by ericchansen** [comment]
Luckily for you, you can restart gradient now with the par_diff_xxx.txt files.

I haven't encountered this despite running many loops with the past several days, and I can't quite make it out because the logging level doesn't seem low enough, so I'm not sure what to do.

Also, you can feel free to give me the 118 parameter loop, and I can easily just make it generate random numbers for the score rather than actually call MacroModel, so it'd still be a quick test.

**Comment by ericchansen** [comment]
Ah, this happened because there was no COMP before your LOOP inside of the loop.py input file.

Let me add something more helpful for this scenario.
