### ISSUE TITLE
OPT in vdW

### ISSUE THREAD

**Issue by peonor** [ericchansen/q2mm#6]
parameters.py crash when mm3.fld contains OPT in vdW parameters.

Command:
$SCHRODINGER/run ~/q2mm-3/parameters.py -pp -pt q

Three lines from within mm3.fld, with line numbers:
1036-  CR     1.9600     0.0560     0.0000                                   0000    O 2
1037:  CM     1.9600     0.0560     0.0000                                   0000    A 3            OPT (PeO Est.)
1038-  O2     1.8200     0.0590     0.0000                                   0000    O 1

Traceback (most recent call last):                                                   
  File "/home/kcjh508/q2mm-3/parameters.py", line 246, in <module>                   
    main(sys.argv[1:])                                                               
  File "/home/kcjh508/q2mm-3/parameters.py", line 190, in main                       
    ff = datatypes.import_ff(opts.ffpath)                                            
  File "/home/kcjh508/q2mm-3/datatypes.py", line 416, in import_ff                   
    "[L{}] Can't read substructure name: {}".format(i + 1, line)                     
AssertionError: [L1037] Can't read substructure name:   CM     1.9600     0.0560     0.0000                                   0000    A 3            OPT (PeO Est.)

File root.log is empty

No error if text "OPT" is removed from the vdW section (only in substructures)

**Comment by peonor** [comment]
The same problem when "OPT" occurs earlier in the file. Problematic, since earlier usage has been to include "OPT" also on parameters in main parameter section. At worst, should be ignored if occurring before Substructure section. At best, accept optimization also of main section parameters!

**Comment by ericchansen** [comment]
What column from the van der Waals parameters are you looking to optimize? Radius, Eps, Offset, Charge or all of the above?

**Comment by peonor** [comment]
Only radius and eps. The offset has to be a decision, not a parameterization (only rarely used, basically only for hydrogen in some environments). The charges are only there as a 20 year old remnant, it’s not actually used, but overwritten by the value in atom.typ.

/Per-Ola

**Comment by ericchansen** [comment]
This issue should all be taken care of. Let me know if I introduced any new bugs. I had to change a lot of how I read and write force field files.

**Comment by peonor** [comment]
Hi Eric,

I’ll be checking during the day.

There are a couple of things I’d like to discuss, I won’t have time to go through the code in detail to get all the answers.

·         The parameter list no longer contains the differentiation step, how do you determine it?

·         By default, you select all torsional parameters. In most cases, changing all will result in serious overfitting, we can only do this if we have good sampling over the entire 360 range. Mostly, we’d select one parameter only, v2 or v3 depending on hybridization. The way I usually do it is that I set most torsional parameters to zero in the FF, set a non-zero value for the ones I want to parameterize, and only pick out those for optimization. And torsions should always be allowed to become negative if the data requires it.

There are a few more things, but I’ll try to work my way through an example first.



I’ve managed to run parameters.py, calculate.py, and loop.py with an input file very similar to the one you provided. I’m right now stuck at compare.py, could be because of the data I’m using, only torsions for now. I found out that if I run ONLY



$SCHRODINGER/run calculate.py –p –jt D1.mae –f mm3.fld



I get an error because the com file does not contain an ELST command, and thus no mmo file is generated. I assume I can fix that by including more data types, will let you know what happens. BTW, the ‘-f mm3.fld’ feels unnecessary, can’t that be default? Crashing without it…



/Per-Ola

**Comment by ericchansen** [comment]
> The parameter list no longer contains the differentiation step, how do you determine it?

The module [constants](https://github.com/ericchansen/q2mm/blob/master/constants.py) contains the default step sizes, and you can change them in there. You can also have them use a relative step size rather than an absolute step size by entering the percentage in quotes. It's explained more in the doc string. (https://github.com/ericchansen/q2mm/blob/master/opt.py) handles any issues where a parameter tries to reach a value it's not allowed to.

> By default, you select all torsional parameters. In most cases, changing all will result in serious overfitting, we can only do this if we have good sampling over the entire 360 range. Mostly, we’d select one parameter only, v2 or v3 depending on hybridization. The way I usually do it is that I set most torsional parameters to zero in the FF, set a non-zero value for the ones I want to parameterize, and only pick out those for optimization. And torsions should always be allowed to become negative if the data requires it.

Making a parameter file is simple, and then you can select whichever parameters you want. See the (README)[https://github.com/ericchansen/q2mm/blob/master/README.md] for more on making a parameter file. Doing that via the command line would just get long and messy, which is why I limit command line parameter control to selecting entire parameter types.

I admit that it would be nice if the [parameters](https://github.com/ericchansen/q2mm/blob/master/parameters.py) module gave torsional parameters and charges the "neg" keyword by default. I think writing that in should only take a minute, so I'll get to it.

> I get an error because the com file does not contain an ELST command, and thus no mmo file is generated. I assume I can fix that by including more data types, will let you know what happens. BTW, the ‘-f mm3.fld’ feels unnecessary, can’t that be default? Crashing without it…

I found out yesterday that when I reworked writing the .com files (~ 1 week ago), that I messed up all the Jaguar structural data types (ja, jb, jt). I think I fixed it yesterday. Can you update your repository and try this again?

For me, I don't keep my Q2MM code in the same directory as my data, so having to specify where the force field is makes sense. I think what I could do is have it try a few things before erroring if you don't include -f mm3.fld. For example, if -d somedir is provided, it could by default pick up somedir/mm3.fld, or if -d isn't provided, then it would check the current directory for mm3.fld.
